### PR TITLE
Update all deps to their latest versions

### PR DESCRIPTION
**Pull request by alshakero**
This will be impossible to review. So I'll explain what I did and you can maybe review my process:

1. Delete all deps folders.
2. Copy all `dependancies` names in `bower.json`. Including `devDependancies`. 
3. Totally empty `bower.json` (leave only `{}`).
4. Run `bower install --save dep1 dep2 dep3`.

Now `bower.json` is fresh and is automatically generated. So it can be a good place to review.

Here is the diff of bower.json, very hard to dig.
```diff
@@ -1,22 +1,19 @@
 {
-  "name": "juicy.github.io",
-  "private": true,
+  "name": "JuicyDeps",
   "dependencies": {
-    "polymer": ">=1.6.0",
-    "jsoneditor": "josdejong/jsoneditor#^5.5.6",
-    "github-markdown-css": "^0.2.0",
-    "marked": "^0.3.5",
-    "d3": "~3.4.12",
-    "fast-json-patch": "~1.0.0",
-    "highlightjs": "~8.7.0",
-    "ace-builds": "~1.2.0"
-  },
-  "devDependencies": {
-    "web-component-tester": "*",
-    "iron-ajax": "PolymerElements/iron-ajax",
-    "iron-icon": "PolymerElements/iron-icon",
-    "iron-iconset-svg": "PolymerElements/iron-iconset-svg",
-    "object.observe": "~0.2.4",
-    "array.observe": "~0.0.1"
+    "polymer": "^2.5.0",
+    "jsoneditor": "^5.13.3",
+    "github-markdown-css": "^2.10.0",
+    "marked": "^0.3.12",
+    "d3": "^4.13.0",
+    "fast-json-patch": "^2.0.6",
+    "highlightjs": "^9.12.0",
+    "ace-builds": "^1.3.1",
+    "web-component-tester": "^6.5.0",
+    "iron-ajax": "^2.1.0",
+    "iron-icon": "^2.0.1",
+    "iron-iconset-svg": "^2.1.1",
+    "object.observe": "^0.2.6",
+    "array.observe": "^0.0.1"
   }
 }
```

Fixes: https://github.com/Juicy/juicy.github.io/issues/7

### CODE REVIEW

**Comment by tomalec** [comment]
I'd keep `"private": true`. 

Speaking of the process, I used to keep `devDependencies` separated from `dependencies` to track packages needes by our elements, from packages needed for example to run web-component-tester in ghpages - but maybe that's not worth it.

Other than that process LGTM

**Comment by warpech** [comment]
> I used to keep devDependencies separated from dependencies to track packages needes by our elements, from packages needed for example to run web-component-tester in ghpages - but maybe that's not worth it.

Did you ever run web-component-tester in ghpages? If not, let's apply YAGNI.

**Comment by tomalec** [comment]
> Did you ever run web-component-tester in gh-pages? If not, let's apply YAGNI.

I use it a lot! http://juicy.github.io/imported-template/test/ Thanks to travis they should pass anyway, but they are easier to debug, to track some behavior. For example when I encounter a strange behavior on real use case. I Go back to those tests put a breakpoint here or there and fiddle.

I believe it's good explanation/showcase of a behavior of the element for newcomers, and sanity check that it works

**Comment by alshakero** [comment]
Please merge if you think it's a good idea. 

(I was gonna ask if I can merge, and thought then you'll answer, then I will merge. Three trips. So I decided to give you the wheel and save a trip 😄 )

**Comment by tomalec** [comment]
I still have two questions to @warpech and @alshakero:
- Do you think it's worth to keep web-components-tester `(/test) results on gh-pages (as in http://juicy.github.io/imported-template/test/)?
- If yes, do you think it's worth keeping separate list of `dependencies` and `devDependencies` to diff packages needed by the element from the packages needed to render demo pages and ghpages?

**Comment by alshakero** [comment]
> If yes, do you think it's worth keeping separate list of dependencies and devDependencies to diff packages needed by the element from the packages needed to render demo pages and ghpages?

This isn't a strong opinion but I don't think it's worth it. I don't look at these repo as a source of truth for what our components need. And it's very hard to maintain it as so. Should we update it everytime we add/remove deps from every juicy-* repo? I guess this is impractical.

**Comment by warpech** [comment]
> Do you think it's worth to keep web-components-tester `(/test) results on gh-pages (as in http://juicy.github.io/imported-template/test)?

You just wrote that you are using it, so sure!

> If yes, do you think it's worth keeping separate list of dependencies and devDependencies to diff packages needed by the element from the packages needed to render demo pages and ghpages?

Sure. Basically, what you're doing here is aggregating `devDependencies` from all components into a common `devDependencies`. I think it is fine. It's a pity Bower can't do it with some flag `bower install --deep`, etc.

**Pull request merged**
